### ISSUE TITLE
Mistyped option doesn't trigger an error

### ISSUE THREAD

**Issue by bjorg** [aws/aws-extensions-for-dotnet-cli#115] opened 2020-04-01 16:39 UTC
It would be nice, if `dotnet lambda` would error out when it encounters an unrecognized command line option.

For example, `dotnet lambda package --foobar` works just fine. Instead, the tool should say that `--foobar` is not supported.

**Comment by klaytaybai** [comment] 2020-04-01 17:06
Thanks for the feedback

**Comment by klaytaybai** [comment] 2020-04-01 21:57
Closing as a duplicate of https://github.com/aws/aws-extensions-for-dotnet-cli/issues/52

**Closed by klaytaybai** 2020-04-01 21:57 UTC
Labels: duplicate, feature-request
