### ISSUE TITLE
.NET 2.1 - MVC's compile time auto-discovery not working

### ISSUE THREAD

**Issue by thammadi** [aws/aws-extensions-for-dotnet-cli#21] opened 2018-07-18 22:20 UTC
Hi Folks,

I had this issue where controllers declared in class libraries where working as expected behind IIS, but not when deployed to AWS Lambda (C# .NET 2.1). This issue however can be resolved temporarily by adding the class library as application part in Web API.

Folks at ASP.NET MVC team, helped identify the issue as described in the below link.
https://github.com/aspnet/Mvc/issues/8095#issuecomment-406060469
[](https://github.com/aspnet/Mvc/issues/8095#issuecomment-406060469)

Can lambda-dotnet-cli also change to compile time graph for auto discovery of controllers?

**Comment by pranavkm** [comment] 2018-07-18 22:33
The issue is specifically this line of code - https://github.com/aws/aws-extensions-for-dotnet-cli/blob/92c7a3d91ad5167d82949c88130c03335fffa18b/src/Amazon.Lambda.Tools/LambdaDotNetCLIWrapper.cs#L101. As of 2.1.x, MVC relies on the compilation context to determine if an assembly references MVC. Setting `PreserveCompilationContext = false` removes these values from the deps file which breaks discovery. 

Would you know why the publish turns off compilation context? If it was meant to avoid the cost of the `refs` directory, you're probably better off simply deleting the folder from the publish output. Publishing with a 2.1.0 compatible SDK should avoid publishing the refs directory to start with.

**Comment by normj** [comment] 2018-07-19 05:15
Thanks for bring this to our attention. I responded on the your GitHub issue to get a bit more clarity. I think if there is no other alternative I'll add an option to allow PreserveCompilationContext be set to true.

**Comment by normj** [comment] 2018-10-15 05:52
Closing as this is now a work around to make this work.

**Closed by normj** 2018-10-15 05:52 UTC
Labels: bug
