### ISSUE TITLE
Support Template Substitutions in YAML files, regardless

### ISSUE THREAD

**Issue by zaus** [aws/aws-extensions-for-dotnet-cli#312] opened 2024-04-29 18:05 UTC
### Describe the feature

Just like https://github.com/aws/aws-extensions-for-dotnet-cli/issues/116 would like to use template substitutions with YAML configuration files.

### Use Case

Specifically trying to transclude Step Function State Machine `DefinitionString` which just needs to smush the contents of a separate JSON file into the YAML, no special processing necessary.

### Proposed Solution

Remove the [templatebody type check](https://github.com/aws/aws-extensions-for-dotnet-cli/blob/master/src/Amazon.Lambda.Tools/LambdaUtilities.cs#L212), and just warn if it's not JSON.  i.e. make it *obvious enough* to the user that it's their own fault for trying it.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Targeted .NET platform

.NET 6+

### CLI extension version

```
Package Id                      Version      Commands
------------------------------------------------------------------------
amazon.lambda.testtool-3.1      0.10.0       dotnet-lambda-test-tool-3.1
amazon.lambda.tools             5.10.4       dotnet-lambda
dotnet-xscgen                   2.0.662      xscgen
```

### Environment details (OS name and version, etc.)

Windows 10

**Comment by ashishdhingra** [comment] 2024-04-29 21:07
@zaus Good afternoon. Could you please advise if this is a duplicate of https://github.com/aws/aws-extensions-for-dotnet-cli/issues/116 or if your scenario is different? Or is it to provide some kind of warning in the output?

Thanks,
Ashish

**Comment by ashishdhingra** [comment] 2024-05-03 16:21
@zaus Good morning. Discussed the issue with the team. Could you please advise if the issue https://github.com/aws/aws-extensions-for-dotnet-cli/issues/314 is fixed, then this issue could be closed!

**Comment by zaus** [comment] 2024-05-03 17:34
Yes that would solve my specific issue.

I still think transclusion regardless of template format would be a neat feature.  Ideally something like how [Serverless Framework variables can pull from other files](https://www.serverless.com/framework/docs/providers/aws/guide/variables#reference-properties-in-other-files), but without bothering to parse the external file for specifics, just embed the file contents where requested.

With this you could split deployment files into separate components (like reusing a file declaring all the Powertools environment variables instead of copy-pasting each time)

**Comment by ashishdhingra** [comment] 2024-05-10 16:36
For YAML parsing, we are relying on Yaml.NET and that package doesn't have support for JSONPath or it's equivalent. Hence, closing this issue.

**Closed by ashishdhingra** 2024-05-10 16:36 UTC
Labels: feature-request, module/cli-ext, needs-review
