### ISSUE TITLE
deploy-function --environment-variables doesn't parse correctly

### ISSUE THREAD

**Issue by denisstepanenko** [aws/aws-extensions-for-dotnet-cli#123] opened 2020-05-07 12:11 UTC
The parameter value passed to --environment-variables doesn't correctly parse the value part if the value contains a semicolon character.

For example, the argument:
_--environment-variables "Key1=""subKey1=subValue1;subKey2=subValue2"";Key2=value2"_

should parse to:
_Key1 -> subKey1=subValue1;subKey2=subValue2
Key2 -> value2_

instead it's parsed as:
_Key1 -> subKey1=subValue1
Key2 -> value2
subKey2 -> subValue2_

However, deploying a lambda with the above arguments through Visual Studio works as expected.

**Comment by ashishdhingra** [comment] 2020-10-21 22:32
Hi @denisstepanenko,

Good afternoon.

Looks like you are not passing the environment variables correctly. Here's the sample Console application:
```C#
using System;

namespace TestEnvironmentVariables
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Number of arguments: " + args.Length);

            for(int i= 0; i<args.Length; i++)
            {
                Console.WriteLine($"args[{i}]: " + args[i]);
            }
        }
    }
}
```
When it:
- Receives the command line arguments `--environment-variables "Key1=""subKey1=subValue1;subKey2=subValue2"";Key2=value2"`, it produces the following output:
```
Number of arguments: 2
args[0]: --environment-variables
args[1]: Key1=subKey1=subValue1;subKey2=subValue2;Key2=value2
```
Notice that the double quotes around `subKey1=subValue1;subKey2=subValue2` get removed. Given the above string, the reported current output is correct. Hence, this could be a .NET Core framework limitation, not a bug in AWS .NET CLI.

- Receives the command line arguments `--environment-variables "Key1=\"subKey1=subValue1;subKey2=subValue2\";Key2=value2"` generate the following output:
```
Number of arguments: 2
args[0]: --environment-variables
args[1]: Key1="subKey1=subValue1;subKey2=subValue2";Key2=value2
```

Kindly note that `""` is an escape sequence for a double quote in C# code, not command line.

Using the command (for a function generated using command `dotnet new lambda.EmptyFunction --name MyFunction
`):
```
dotnet lambda deploy-function MyFunction --function-role issue123-lambdarole --environment-variables "Key1=\"subKey1=subValue1;subKey2=subValue2\";Key2=value2"
```
correctly sets the environment variables in Lambda function configuration:
<img width="1067" alt="Screen Shot 2020-10-21 at 3 27 52 PM" src="https://user-images.githubusercontent.com/67916761/96793892-0f7eb280-13b2-11eb-84f1-03965a31159c.png">

Closing this issue since the above guidance works correctly. Feel free to open a new issue if you encounter any other error.

Thanks,
Ashish

**Closed by ashishdhingra** 2020-10-21 22:32 UTC
Labels: bug, module/cli-ext, needs-triage
