### ISSUE TITLE
Install on Ubuntu 18.04 with DotnetToolSettings.xml not found in packate

### ISSUE THREAD

**Issue by felixMasonJncc** [aws/aws-extensions-for-dotnet-cli#34] opened 2018-09-27 11:33 UTC
I was trying to install this on an 18.04 instace on aws.

To recreate

Spin up an instance of Ubuntu 18.04LTS on amazon - (ami: ami-00035f41c82244dab)
Free tier is fine
Install dotnet as per instructions here: https://www.microsoft.com/net/download/linux-package-manager/ubuntu18-04/sdk-current

Install the elastic beanstalk tools (the others fail in the same way)
   
    dotnet tool install -g Amazon.ElasticBeanstalk.Tools

Fails with: 

"The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'amazon.elasticbeanstalk.tools' failed to install. Please contact the tool author for assistance."

Obsevations:

I'm running ubuntu 18.04 locally with the Mate desktop and got the tools to install and run fine, this may be a bug downstream? I'm using zsh locally if that has any impact.

**Comment by l8nite** [comment] 2018-11-20 21:46
Running into this here too for `Amazon.Lambda.Tools` - any ideas what's going on?

**Comment by normj** [comment] 2019-03-08 00:28
Can anybody let me know if they are still seeing this problem? It looks like there was an issue with the dotnet CLI tooling that was fixed in a patch. https://github.com/dotnet/cli/issues/10101

**Comment by normj** [comment] 2019-04-01 05:21
Resolving for lack of activity

**Closed by normj** 2019-04-01 05:21 UTC

**Comment by acds** [comment] 2019-04-18 23:09
@normj - timing - just seen this with Amazon.Lambda.Tools on MacOS 10.14.4

```
$ dotnet tool install --global Amazon.Lambda.Tools --version 3.2.1
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'amazon.lambda.tools' failed to install. Please contact the tool author for assistance.
```

**Comment by zloveless** [comment] 2019-04-18 23:13
Just seen this in VSTS (Azure DevOps) on Ubuntu 16.04.

```
[command] dotnet tool install -g Amazon.Lambda.Tools
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'amazon.lambda.tools' failed to install. Please contact the tool author for assistance.```

**Comment by drvora** [comment] 2019-04-19 13:12
Just saw this in AWS codebuild under Ubuntu 

[Container] 2019/04/19 12:40:31 Running command dotnet tool install -g Amazon.Lambda.Tools
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'amazon.lambda.tools' failed to install. Please contact the tool author for assistance.

Last successful build was 15 hours ago. If that helps. Same buildspec.yml, no change.

**Comment by mattshafer** [comment] 2019-04-19 15:43
Looks like the Amazon.Lambda.Tools package was updates 17 hours. https://www.nuget.org/packages/Amazon.Lambda.Tools/

This should work as a workaround for anyone stuck on this:
dotnet tool install -g Amazon.Lambda.Tools --version 3.2.0

**Comment by normj** [comment] 2019-04-19 16:22
For the issue caused by the new release use the following issue to track it https://github.com/aws/aws-extensions-for-dotnet-cli/issues/76
